Adding Unique ID for Sensors
madpilot/hass-amber-electric pull request #15
Opened 2021-07-14 06:42 UTC by troykelly

Sensors need a `unique_id` per [here](https://developers.home-assistant.io/docs/entity_registry_index/).

2021-07-14 06:47 UTC, troykelly commented
<img width="1010" alt="Screen Shot 2021-07-14 at 4 45 51 pm" src="https://user-images.githubusercontent.com/4564803/125575949-b72e5895-c7e4-4de5-881a-27f69e233ef1.png">

I've got a `PR` in for [wheel](https://github.com/home-assistant/wheels-custom-integrations/pull/460).
`brand` can just be a rename of amber_electric [here](https://github.com/home-assistant/brands/tree/master/custom_integrations).

2021-07-14 11:54 UTC, madpilot requested changes
Thanks for the PR - a couple of small changes around the unique_id (See comments below)

2021-07-14 11:54 UTC, madpilot commented on custom_components/amberelectric/sensor.py
> +        return "%s_%s_%s" % (self._platform_name, self._channel_type, "Price")
`_platform_name` isn't guaranteed to be unique, and isn't immutable. Better to use site id, which will require a bit of a refactor so `AmberPriceSensor` takes it as a parameter.

Also, use slugify (`from homeassistant.util import slugify` when generating the string.

2021-07-14 11:54 UTC, madpilot commented on custom_components/amberelectric/sensor.py
> +        return "%s_%s" % (self._platform_name, "Renewables")
See above comment

2021-07-14 11:54 UTC, madpilot commented on custom_components/amberelectric/sensor.py
> +        return "%s_%s_%s" % (self._platform_name, self._channel_type, "Forecast")
See above comment

2021-07-14 11:54 UTC, madpilot commented on custom_components/amberelectric/sensor.py
> +        return "%s_%s" % (self._platform_name, "PriceSpike")
See above comment

2021-07-14 12:27 UTC, madpilot commented
I have no idea what the "The repository is missing topics" error means. Any ideas? If not, can you add an ignore: https://github.com/hacs/action#ignorable-checks

2021-07-14 13:42 UTC, madpilot commented
I actually just did this: https://github.com/madpilot/hass-amber-electric/commit/e6783e6303134e9be1761c8a2f9c7e573632954d

2021-07-14 13:42 UTC, closed without merging

2021-07-15 06:25 UTC, troykelly commented
@madpilot Thank you!
I wasn't sure when I'd get a minute to get back to this.
Great work with the integration.